name: "Install dotfiles"
description: "Install dotfiles"
author: "Gerard Braad <me@gbraad.nl>"
runs:
  using: "composite"
  steps:
    - name: Install dotfiles
      run: |
        curl -fsSL https://dotfiles.gbraad.nl/install.sh | sh
        chsh -s $(which zsh)
      shell: bash
